export const BOARD_WIDTH = 360;
const BOARD_ASPECT_RATIO = 14 / 9;
const DANGER_LINE_RATIO = 0.15;
const SPAWN_Y_RATIO = DANGER_LINE_RATIO / 2;

export const BOARD_HEIGHT = BOARD_WIDTH * BOARD_ASPECT_RATIO;
export const SPAWN_Y = BOARD_HEIGHT * SPAWN_Y_RATIO;
export const DANGER_LINE = BOARD_HEIGHT * DANGER_LINE_RATIO;
